### ISSUE TITLE
Allow to set optional layer id

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft#409]
Currently layers are accessible like a Zero-based indexed array. This hasn't been a problem until recently because blended layers were exposed in raster format (png), but as we are now exposing vector formats we want to have an easier way to identify layers within set of them.

## TODO
 - [x] Be able to use an optional `id` in the layer, when user provides duplicated `id` for different layers it should raise an error.

When `id` is not provided:
 - [ ] ~~Use table name as as layer `id`, if it's already used, fallback to next rule~~.
 - [ ] ~~Fallback to layer `id` based on cartocss rules, if it's already in use fallback to next rule. Ref: https://github.com/CartoDB/grainstore/issues/106~~.
 - [x] Keep the current `id` (`"layer{layerIndex}"`) if any of the previous options cannot be applied.

**Comment by jaakla** [comment]
I would expect layer ID to match with table name by default, so using Multilayer-API.md sample:
```
{
    "version": "1.0.1",
    "layers": [
        {
            "type": "cartodb",
            "options": {
                "cartocss_version": "2.1.1",
                "cartocss": "#layer { polygon-fill: #FFF; }",
                "sql": "select * from european_countries_e"
            }
        }
    ]
}
```
one should have 
```
...
                "cartocss": "#european_countries_e { polygon-fill: #FFF; }",
                "sql": "select * from european_countries_e"
            }
...
```
However, some may have several tables with same names, so best solution would be to support ID/name like

```
{
    "version": "1.0.1",
    "layers": [
        {
            "type": "cartodb",
            "id": "european_countries",
            "options": {
                "cartocss_version": "2.1.1",
                "cartocss": "#european_countries { polygon-fill: #FFF; }",
                "sql": "select * from european_countries_e"
            }
        }
    ]
}
```

**Comment by rochoa** [comment]
Your last proposal is what first item in todo list was about, sorry if I was not clear enough about it.

Also: extracting the table name is not always possible, e.g. when using functions, so we need to fallback to other options in those cases.

I changed a bit the issue description to address these problems.

**Comment by rochoa** [comment]
For now it seems to be enough to be able to set the id in the MapConfig as per https://github.com/CartoDB/Windshaft/pull/485. We will reopen if needed.

**Comment by jaakla** [comment]
It does not completely resolve issue that maps created in Builder do not work, they still use default layer0, layer1... IDs which never match with CartoCSS generated by Builder. Issue in Builder?
