### ISSUE TITLE
[node-v6] Node v6 LTS support

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft#519]
Support for Node 0.10.x has ended in October 2016. We need to migrate to the latest Node LTS version (`v6.9.1`), for that we need:
 
 - [x] Check what dependencies don't work in Node v6 and need to be updated.
 - [x] Update forked repos and apply required changes.
 - [x] Implement changes to be Node v6 compatible.
 - [x] Check what CartoCSS rules are no longer supported and prepare a tool for migrating them.
 - [x] Check if mapnik@3.0.x uses the latest changes of TWKB we have in our 2.3.x fork

## TODO
 - [x] #512 Upgrade abaculus
 - [x] #513 Upgrade node-canvas
 - [x] #514 Upgrade carto
 - [x] #515 Upgrade grainstore -> [grainstore#116](https://github.com/CartoDB/grainstore/issues/116)
 - [x] #516 Upgrade redis-mpool
 - [x] #517 Upgrade tilelive-bridge
 - [x] #518 Upgrade tilelive-mapnik

**Comment by dgaubert** [comment]
PR: #533
